In [5]:
import numpy as np
"""numpy is faster than lists as it has to store only one singe type of objects hence it has to store the same datatype in less memory it reads less bytes of memory faster"""

'numpy is faster than lists as it has to store only one singe type of objects hence it has to store the same datatype in less memory it reads less bytes of memory faster'

In [6]:
"""In list memory is not contiguous but in numpy array memory is contiguous
SIMD vector processing
         lists                                          numpy
         1.append,remove
"""

'In list memory is not contiguous but in numpy array memory is contiguous\nSIMD vector processing\n         lists                                          numpy\n         1.append,remove\n'

In [3]:
#basics
a=np.array([2,3,4])
a

array([2, 3, 4])

In [9]:
#multidimmesional arrray
b=np.array([[6,5,4,9],[7,5,4,2.3]])
b

array([[6. , 5. , 4. , 9. ],
       [7. , 5. , 4. , 2.3]])

In [10]:
#get dimmensions
b.ndim

2

In [11]:
#get shape
b.shape

(2, 4)

In [13]:
#gettype
print(a.dtype)
b.dtype

int32


dtype('float64')

In [14]:
"""Acessing /changing specific elements ,rows ,columns"""

'Acessing /changing specific elements ,rows ,columns'

In [15]:
b[1,2]

4.0

In [16]:
b[:,2]=[2,2]

In [17]:
b

array([[6. , 5. , 2. , 9. ],
       [7. , 5. , 2. , 2.3]])

In [18]:
"""initializing matrix"""

'initializing matrix'

In [21]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.ones((2,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [23]:
#any other number
np.full((2,2),4)

array([[4, 4],
       [4, 4]])

In [24]:
#random decimal 
np.random.rand(2,3)

array([[0.85014117, 0.34675212, 0.12514808],
       [0.43100333, 0.40868248, 0.10967368]])

In [26]:
#random integer values
np.random.randint(3,size=(3,3))#(number upto which,shape)

array([[2, 1, 1],
       [0, 1, 1],
       [1, 0, 1]])

In [28]:
 #identity matrix
np.identity(3,"int32")  

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [33]:
 arr=np.array([[1,2,3]])
 r1=np.repeat(arr,3,axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [37]:
output=np.ones((5,5),"int32")

In [38]:
output

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [43]:
output[1:4,1:4]=0
output

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [44]:
output[2][2]=9

In [46]:
output

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [47]:
#shallow copy and deep copy
a=np.array([1,2,3])
a

array([1, 2, 3])

In [48]:
b=a
print(b)

[1 2 3]


In [49]:
b[0]=100

In [50]:
b

array([100,   2,   3])

In [51]:
a

array([100,   2,   3])

In [52]:
b=a.copy()

In [53]:
b[0]=20
b

array([20,  2,  3])

In [54]:
a

array([100,   2,   3])

In [55]:
#mathematics
a*2

array([200,   4,   6])

In [56]:
a+2

array([102,   4,   5])

In [57]:
a*b

array([2000,    4,    9])

In [58]:
ab=np.array([[20,25,23],[90,45,25],[75,58,8]])
bc=np.array([[20,25,23],[90,45,25],[75,58,8]])
ab*bc

array([[ 400,  625,  529],
       [8100, 2025,  625],
       [5625, 3364,   64]])

In [59]:
np.cos(a) 

array([ 0.86231887, -0.41614684, -0.9899925 ])

In [60]:
np.sin(a)

array([-0.50636564,  0.90929743,  0.14112001])

In [62]:
"""linear algebra"""


'linear algebra'

In [63]:
np.linalg.det(ab)

49510.00000000002

In [64]:
"""determinants
trace
eigen values
matrix norm
inverse"""


'determinants\ntrace\neigen values\nmatrix norm\ninverse'

In [65]:
"stats"

'stats'

In [66]:
np.min(ab)

8

In [67]:
np.max(ab)

90

In [69]:
ab.reshape((9,1))

array([[20],
       [25],
       [23],
       [90],
       [45],
       [25],
       [75],
       [58],
       [ 8]])

In [77]:
#horizontal stach and vertical stack
v=np.ones((1,))
v1=np.zeros((1,))
v2=np.vstack((v,v1,v))
v3=np.hstack((v,v1,v))
v2,v3

(array([[1.],
        [0.],
        [1.]]),
 array([1., 0., 1.]))