In [2]:
import numpy as np

In [1]:
myarr=np.array([3,6,37,7])

NameError: name 'np' is not defined

In [7]:

a=np.identity(3)

In [8]:
np.linalg.det(a)

1.0

In [10]:
np.linalg.inv(a)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
b=np.array([[20,12,50],[85,2,30],[20,19,20]])

In [13]:
b

array([[20, 12, 50],
       [85,  2, 30],
       [20, 19, 20]])

In [15]:
c=np.linalg.inv(b)

In [17]:
b*c

array([[-0.19290264,  0.15505005,  0.23657871],
       [-1.70154686, -0.02183803,  1.99272066],
       [ 0.57324841, -0.04840764, -0.3566879 ]])

In [18]:
np.linalg.det(b*c)

0.08535180878306943